##### Creating a matrix

In [2]:
import numpy as np

In [34]:
M1 = np.array([[3,4,5],[7,1,9]])

In [35]:
M1

array([[3, 4, 5],
       [7, 1, 9]])

In [36]:
M1.shape

(2, 3)

In [37]:
M2 = np.array([[3,4],[7,9],[6,2],[8,5]])
M2

array([[3, 4],
       [7, 9],
       [6, 2],
       [8, 5]])

In [38]:
M2.shape

(4, 2)

In [39]:
M1.size

6

In [40]:
M2.size

8

In [41]:
type(M1)

numpy.ndarray

In [42]:
v1 = np.array([7,3,1,5,2,9,0,5,6])

In [43]:
v1

array([7, 3, 1, 5, 2, 9, 0, 5, 6])

In [44]:
v1.size

9

In [45]:
M3 = v1.reshape(3,3)

In [46]:
M3

array([[7, 3, 1],
       [5, 2, 9],
       [0, 5, 6]])

In [47]:
np.reshape(v1, (3 ,3) )

array([[7, 3, 1],
       [5, 2, 9],
       [0, 5, 6]])

In [48]:
v1.reshape(3,4)

ValueError: cannot reshape array of size 9 into shape (3,4)

In [22]:
M1

array([[3, 4, 5],
       [7, 1, 9]])

In [23]:
M1.reshape(6)

array([3, 4, 5, 7, 1, 9])

In [24]:
M1.flatten()

array([3, 4, 5, 7, 1, 9])

In [25]:
v1.reshape(3,3)

array([[7, 3, 1],
       [5, 2, 9],
       [0, 5, 6]])

In [26]:
v1.reshape(-1,3)

array([[7, 3, 1],
       [5, 2, 9],
       [0, 5, 6]])

In [27]:
v1.reshape(-1,1)

array([[7],
       [3],
       [1],
       [5],
       [2],
       [9],
       [0],
       [5],
       [6]])

In [28]:
v1.reshape(3, -1)

array([[7, 3, 1],
       [5, 2, 9],
       [0, 5, 6]])

In [29]:
M1

array([[3, 4, 5],
       [7, 1, 9]])

In [30]:
M1.dtype

dtype('int64')

In [31]:
M1 = np.array([[3,4,5],[7,1,9]], dtype = np.int8)

In [32]:
M1

array([[3, 4, 5],
       [7, 1, 9]], dtype=int8)

In [49]:
M1[0]

array([3, 4, 5])

In [50]:
M1[1]

array([7, 1, 9])

In [51]:
M3

array([[7, 3, 1],
       [5, 2, 9],
       [0, 5, 6]])

In [52]:
M3[0][1]

3

In [53]:
M3[0][1] = 8

In [54]:
M3

array([[7, 8, 1],
       [5, 2, 9],
       [0, 5, 6]])

In [55]:
M3[0,1]

8

In [57]:
# R -> 1 to 2 (3 -1)
# C -> 0 to 1 (2 -1)
M3[1:3,0:2]

array([[5, 2],
       [0, 5]])

In [59]:
M3[1:,0:]

array([[5, 2, 9],
       [0, 5, 6]])

In [60]:
M3[:3,:2]

array([[7, 8],
       [5, 2],
       [0, 5]])

In [61]:
M3[:,:]

array([[7, 8, 1],
       [5, 2, 9],
       [0, 5, 6]])

In [62]:
M4 = M3

In [63]:
M4

array([[7, 8, 1],
       [5, 2, 9],
       [0, 5, 6]])

In [64]:
M4[2][2]

6

In [65]:
M4[2][2] = 10

In [66]:
M4

array([[ 7,  8,  1],
       [ 5,  2,  9],
       [ 0,  5, 10]])

In [67]:
M3

array([[ 7,  8,  1],
       [ 5,  2,  9],
       [ 0,  5, 10]])

In [68]:
id(M3)

137874558310064

In [69]:
id(M4)

137874558310064

In [72]:
# create a shallow copy of the data
M4 = M3.copy()

In [71]:
M4

array([[ 7,  8,  1],
       [ 5,  2,  9],
       [ 0,  5, 10]])

In [73]:
id(M3)

137874558310064

In [74]:
id(M4)

137874624002064

#### Matrix Operations

##### Matrix Addition

In [77]:
M5 = np.array([[7,3,1],[5,2,9],[0,5,6],[6,1,2]])

In [78]:
M6 = np.array([[9,2,1],[8,8,2],[5,6,4],[0,1,3]])

In [79]:
M5

array([[7, 3, 1],
       [5, 2, 9],
       [0, 5, 6],
       [6, 1, 2]])

In [80]:
M6

array([[9, 2, 1],
       [8, 8, 2],
       [5, 6, 4],
       [0, 1, 3]])

In [81]:
M7 = M5 + M6

In [82]:
M7

array([[16,  5,  2],
       [13, 10, 11],
       [ 5, 11, 10],
       [ 6,  2,  5]])

In [83]:
M5 + M3

ValueError: operands could not be broadcast together with shapes (4,3) (3,3) 

##### Matrix Subtraction

In [86]:
M8 = M5 - M6

In [87]:
M8

array([[-2,  1,  0],
       [-3, -6,  7],
       [-5, -1,  2],
       [ 6,  0, -1]])

##### Matrix Scalar Operations

In [90]:
M4 + 2

array([[ 9, 10,  3],
       [ 7,  4, 11],
       [ 2,  7, 12]])

In [91]:
M4 - 3

array([[ 4,  5, -2],
       [ 2, -1,  6],
       [-3,  2,  7]])

In [92]:
M4 * 2

array([[14, 16,  2],
       [10,  4, 18],
       [ 0, 10, 20]])

In [94]:
2 * M6 + M5

array([[25,  7,  3],
       [21, 18, 13],
       [10, 17, 14],
       [ 6,  3,  8]])

In [95]:
-1 * M4

array([[ -7,  -8,  -1],
       [ -5,  -2,  -9],
       [  0,  -5, -10]])

In [96]:
2 * M5 + 2 * M6 

array([[32, 10,  4],
       [26, 20, 22],
       [10, 22, 20],
       [12,  4, 10]])

In [97]:
2 * (M5 + M6)

array([[32, 10,  4],
       [26, 20, 22],
       [10, 22, 20],
       [12,  4, 10]])

##### Matrix Multiplication

In [99]:
M4.shape

(3, 3)

In [100]:
M5.shape

(4, 3)

In [101]:
M6.shape

(4, 3)

In [102]:
M5 * M4

ValueError: operands could not be broadcast together with shapes (4,3) (3,3) 

In [103]:
np.matmul(M5, M4)

array([[ 64,  67,  44],
       [ 45,  89, 113],
       [ 25,  40, 105],
       [ 47,  60,  35]])

In [104]:
M5 @ M4

array([[ 64,  67,  44],
       [ 45,  89, 113],
       [ 25,  40, 105],
       [ 47,  60,  35]])

In [105]:
M6 @ M4

array([[ 73,  81,  37],
       [ 96,  90, 100],
       [ 65,  72,  99],
       [  5,  17,  39]])

In [106]:
M4 @ M5

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

##### Transpose of the matrix

In [108]:
M5

array([[7, 3, 1],
       [5, 2, 9],
       [0, 5, 6],
       [6, 1, 2]])

In [109]:
np.transpose(M5)

array([[7, 5, 0, 6],
       [3, 2, 5, 1],
       [1, 9, 6, 2]])

In [110]:
np.transpose(M3)

array([[ 7,  5,  0],
       [ 8,  2,  5],
       [ 1,  9, 10]])

In [111]:
M5.T

array([[7, 5, 0, 6],
       [3, 2, 5, 1],
       [1, 9, 6, 2]])

In [112]:
M3.T

array([[ 7,  5,  0],
       [ 8,  2,  5],
       [ 1,  9, 10]])

In [113]:
M3.T.shape

(3, 3)

In [114]:
M5.shape

(4, 3)

In [115]:
M5.T.shape

(3, 4)

In [117]:
M3 @ M5

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [118]:
M3 @ M5.T

array([[ 74,  60,  46,  52],
       [ 50, 110,  64,  50],
       [ 25, 100,  85,  25]])

In [121]:
M5

array([[7, 3, 1],
       [5, 2, 9],
       [0, 5, 6],
       [6, 1, 2]])

In [122]:
M5.T.T

array([[7, 3, 1],
       [5, 2, 9],
       [0, 5, 6],
       [6, 1, 2]])

In [123]:
M3 + M4

array([[14, 16,  2],
       [10,  4, 18],
       [ 0, 10, 20]])

In [124]:
(M3 + M4).T

array([[14, 10,  0],
       [16,  4, 10],
       [ 2, 18, 20]])

In [125]:
M3.T + M4.T

array([[14, 10,  0],
       [16,  4, 10],
       [ 2, 18, 20]])

##### Trace of Matrix

In [127]:
M3

array([[ 7,  8,  1],
       [ 5,  2,  9],
       [ 0,  5, 10]])

In [128]:
for row in M3:
    print(row)

[7 8 1]
[5 2 9]
[ 0  5 10]


In [129]:
for row in M3:
    for val in row:
        print(val)

7
8
1
5
2
9
0
5
10


In [131]:
add = 0
rn = 0
for row in M3:
    print(row[rn])
    add += row[rn]
    rn += 1

7
2
10


In [132]:
print(add)

19


In [133]:
np.trace(M3)

19

In [134]:
M3.trace()

19

In [136]:
M5

array([[7, 3, 1],
       [5, 2, 9],
       [0, 5, 6],
       [6, 1, 2]])

In [137]:
M5.trace()

15

In [138]:
np.trace(M3 @ M4)

323

In [139]:
np.trace(M4 @ M3)

323

In [140]:
M3.T.trace()

19

In [141]:
M3.trace()

19

##### Determinant of Matrix

In [143]:
M3

array([[ 7,  8,  1],
       [ 5,  2,  9],
       [ 0,  5, 10]])

In [144]:
np.linalg.det(M3)

-549.9999999999998

In [145]:
7 * (2 * 10 - 9 * 5) - 8 * (5 * 10 - 9 * 0) + 1 * (5 * 5 - 2 * 0)

-550

##### Inverse of matrix

In [149]:
M3

array([[ 7,  8,  1],
       [ 5,  2,  9],
       [ 0,  5, 10]])

In [150]:
np.linalg.inv(M3)

array([[ 0.04545455,  0.13636364, -0.12727273],
       [ 0.09090909, -0.12727273,  0.10545455],
       [-0.04545455,  0.06363636,  0.04727273]])

##### Rank of matrix

In [154]:
M3

array([[ 7,  8,  1],
       [ 5,  2,  9],
       [ 0,  5, 10]])

In [155]:
np.linalg.matrix_rank(M3)

3

In [162]:
M7 = np.array([[1,2,3],[6,2,9],[2,4,6]])

In [163]:
M7

array([[1, 2, 3],
       [6, 2, 9],
       [2, 4, 6]])

In [164]:
np.linalg.matrix_rank(M7)

2

In [165]:
M8 = np.array([[1,2,3],[3,6,9],[2,4,6]])

In [166]:
np.linalg.matrix_rank(M8)

1

In [168]:
M7[0] * 2

array([2, 4, 6])

In [169]:
M8

array([[1, 2, 3],
       [3, 6, 9],
       [2, 4, 6]])

In [170]:
M8[0] * 2

array([2, 4, 6])

In [171]:
M8[0] * 3

array([3, 6, 9])

#### Types of Matrices

##### Row Matrix

In [7]:
R = np.array([[4,7,4,2,7,8]])

In [8]:
R

array([[4, 7, 4, 2, 7, 8]])

In [9]:
R.shape

(1, 6)

In [10]:
R.reshape(3,2)

array([[4, 7],
       [4, 2],
       [7, 8]])

##### Column Matrix

In [15]:
C = np.array([[4],[7],[4],[2],[7],[8]])

In [16]:
C

array([[4],
       [7],
       [4],
       [2],
       [7],
       [8]])

In [17]:
C.shape

(6, 1)

In [18]:
C.reshape(3,2)

array([[4, 7],
       [4, 2],
       [7, 8]])

In [19]:
C.reshape(1,6)

array([[4, 7, 4, 2, 7, 8]])

In [21]:
R.reshape(6,1)

array([[4],
       [7],
       [4],
       [2],
       [7],
       [8]])

In [22]:
C.T

array([[4, 7, 4, 2, 7, 8]])

In [23]:
R.T

array([[4],
       [7],
       [4],
       [2],
       [7],
       [8]])

##### Square Matrix

In [26]:
M1 = np.array([[5,6,7],[2,8,9],[2,1,4]])

In [27]:
M1

array([[5, 6, 7],
       [2, 8, 9],
       [2, 1, 4]])

In [28]:
def isSquareMatrix(M):
    if M.shape[0] == M.shape[1]:
        return True
    else:
        return False

In [29]:
isSquareMatrix(M1)

True

In [30]:
isSquareMatrix(R)

False

##### Rectangular Matrix

In [32]:
M2 = np.array([[5,6,7],[2,8,9]])

In [33]:
M2

array([[5, 6, 7],
       [2, 8, 9]])

In [34]:
def isRectangularMatrix(M):
    if M.shape[0] == M.shape[1]:
        return False
    else:
        return True

In [35]:
isRectangularMatrix(M2)

True

In [36]:
isRectangularMatrix(M1)

False

In [37]:
M1.shape

(3, 3)

In [38]:
M1[0]

array([5, 6, 7])

In [41]:
M3 = np.zeros([4,4], dtype=np.int8)

In [42]:
M3

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [43]:
M3 = M3 + 4

In [44]:
M3

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]], dtype=int8)

##### Diagonal Matrix

In [48]:
D = np.array([[1,0,0],[0,8,0],[0,0,9]])

In [49]:
D

array([[1, 0, 0],
       [0, 8, 0],
       [0, 0, 9]])

In [50]:
D = np.zeros([4,4], dtype=np.int8)

In [51]:
D

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [52]:
for i in range(4):
    D[i][i] = 6

In [53]:
D

array([[6, 0, 0, 0],
       [0, 6, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 6]], dtype=int8)

In [59]:
def isDiagonalMatrix(M):
    for i in range(M.shape[0]):
        for j in range(M.shape[1]):
            if i != j and M[i][j] != 0:
                return False
    return True

In [60]:
isDiagonalMatrix(D)

True

In [62]:
isDiagonalMatrix(M1)

False

##### Identity Matrix

In [64]:
I = np.zeros([4,4], dtype=np.int8)

In [65]:
I

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [66]:
for i in range(4):
    I[i][i] = 1

In [67]:
I

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [68]:
I.diagonal()

array([1, 1, 1, 1], dtype=int8)

In [69]:
np.diag(I)

array([1, 1, 1, 1], dtype=int8)

##### Symmetric Matrix

In [71]:
S1 = np.array([[2,3,6],[3,4,5],[6,5,9]])

In [72]:
S1

array([[2, 3, 6],
       [3, 4, 5],
       [6, 5, 9]])

In [73]:
S1.T

array([[2, 3, 6],
       [3, 4, 5],
       [6, 5, 9]])

In [75]:
S1 == S1.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [76]:
(S1 == S1.T).sum()

9

In [77]:
S1.size

9

In [78]:
def isSymmetricMatrix(M):
    if (M == M.T).sum() == M.size:
        return True
    else:
        return False

In [79]:
isSymmetricMatrix(S1)

True

In [80]:
isSymmetricMatrix(M1)

False

##### Skew-Symmetric Matrix

In [83]:
S2 = np.array([[0, 3],[-3, 0]])

In [84]:
S2

array([[ 0,  3],
       [-3,  0]])

In [85]:
S2.T

array([[ 0, -3],
       [ 3,  0]])

In [86]:
-S2

array([[ 0, -3],
       [ 3,  0]])

#### Eigenvector and Eigenvalues

In [88]:
# Define a matrix
A = np.array([[-6, 3], [4, 5]])

In [89]:
A

array([[-6,  3],
       [ 4,  5]])

In [93]:
# calculate eigenvector and eigenvalues
eval, evect = np.linalg.eig(A)

In [94]:
evect

array([[-0.9486833 , -0.24253563],
       [ 0.31622777, -0.9701425 ]])

In [95]:
eval

array([-7.,  6.])

In [96]:
A @ evect

array([[ 6.64078309, -1.45521375],
       [-2.21359436, -5.820855  ]])

In [98]:
eval * evect

array([[ 6.64078309, -1.45521375],
       [-2.21359436, -5.820855  ]])

In [ ]:
# break